global using System.ComponentModel;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Reactive;
global using System.Reactive.Disposables;
global using System.Reactive.Linq;
global using System.Runtime.Serialization;
global using System.Threading.Tasks;
global using NotNull = System.Diagnostics.CodeAnalysis.NotNullAttribute;
global using ViewModelBase = DDS.Core.ViewModels.ViewModelBase;
global using Avalonia.ReactiveUI;
global using Avalonia.Controls;
global using DDS.Avalonia.Controls;
global using DDS.Core.ViewModels;
global using DDS.Avalonia.Views;
global using DDS.Avalonia.Services;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using JetBrains.Annotations;
global using Microsoft.Extensions.DependencyInjection;
global using ReactiveUI;
global using ReactiveUI.Fody.Helpers;
