global using ViewModelBase = DDS.ViewModels.ViewModelBase;
global using DDS.Controls;
global using DDS.ViewModels;
global using DDS.Views;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Microsoft.Extensions.DependencyInjection;
global using ReactiveUI;
global using Avalonia.ReactiveUI;
global using Avalonia.Controls;
global using System.Reactive;
global using System.Reactive.Linq;
global using JetBrains.Annotations;